server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      uri: mongodb+srv://<login>:<password>@spring-ddd-cicd-example.1ua8ah5.mongodb.net/spring-ddd-cicd-example
